name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # TODO: PlenaryBustedDirectory seems not to run on Windows
          # - windows-latest
        version:
          - v0.9.0
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Checkout nvim-lspconfig
        uses: actions/checkout@v3
        with:
          repository: neovim/nvim-lspconfig
          path: nvim-lspconfig
      - name: Checkout plenary.nvim
        uses: actions/checkout@v3
        with:
          repository: nvim-lua/plenary.nvim
          path: plenary.nvim
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true
          version: ${{ matrix.version }}
      - name: Run tests
        env:
          PLENARY_PATH: plenary.nvim
          EXE: ${{ steps.nvim.outputs.executable }}
        run: |-
          TEST_DIR=lua/frecency/tests/
          MINIMAL_LUA=${TEST_DIR}minimal.lua
          NVIM=$(perl -e '$_ = $ENV{EXE}; s,\\,/,g; print')
          $NVIM --headless --clean -u $MINIMAL_LUA -c "PlenaryBustedDirectory $TEST_DIR {minimal_init = '$MINIMAL_LUA'}"
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Lint sources
        env:
          LSP_CONFIG_PATH: nvim-lspconfig
          EXE: ${{ steps.nvim.outputs.executable }}
        run: |-
          NVIM=$(perl -e '$_ = $ENV{EXE}; s,\\,/,g; print')
          bin/lint.sh
